/**
 * Provider type definitions
 * Generated to match backend schemas exactly
 */

export interface ProviderBase {
  name: string;
  description?: string;
  email: string;
  phone?: string;
  website?: string;
  address?: string;
  logo_url?: string;
}

export interface ProviderCreate extends ProviderBase {
  // All fields from ProviderBase
  // provider_id will be generated by backend
}

export interface ProviderUpdate {
  name?: string;
  description?: string;
  email?: string;
  phone?: string;
  website?: string;
  address?: string;
  logo_url?: string;
  is_active?: boolean;
}

export interface Provider extends ProviderBase {
  provider_id: string;  // Primary key for providers
  created_at: string;
  updated_at: string;
  is_active: boolean;
}

// Form validation rules (matching backend)
export const ProviderValidation = {
  name: {
    required: true,
    minLength: 1,
    maxLength: 255,
  },
  description: {
    maxLength: 1000,
  },
  email: {
    required: true,
    format: 'email',
  },
  phone: {
    maxLength: 20,
    pattern: /^[\d\s\-\(\)\+\.]+$/,
    minDigits: 10,
  },
  website: {
    format: 'url',
    maxLength: 2083,
  },
  address: {
    maxLength: 500,
  },
  logo_url: {
    maxLength: 500,
  },
} as const;